package edu.nyu.cs.cs2580.ranking_model;

/**
 * Abstract class representing a ranking model for the Ranker. 
 * 
 */
public abstract class Model
{
	/**
	 * Returns the score generated by the given Model
	 * 
	 * @return
	 */
	public abstract Float getScore();
}
